### ISSUE TITLE
楼主你的SDK在哪下载的。能否提供一份。

### ISSUE THREAD

**Issue by showbar** [JerryZheng89/DemoProject_MM32#1]
我现在使用MM32F103芯片，我从淘宝上下载的SDK，无法使用，测试使用楼主这个SDK是正常的，对比发现，对RCC这部分定义不同，版本日期也不同，淘宝上的日期新但版本没有楼主的高，不知道什么问题。所以能否提供下楼主使用SDK和官方历程（官方我联系不上电话空号，邮箱不存在）,我的邮箱地址：wangzhibo0902@sina.com

**Comment by JerryZheng89** [comment]
SDK版本和芯片的版本要对应，不然可能有问题， 原始SDK我要找找看了，好久没用了，  DemoProject_MM32/Device
/MM32F103xCxE_o  这个目录下的SDK不能用吗？

**Comment by showbar** [comment]
> SDK版本和芯片的版本要对应，不然可能有问题， 原始SDK我要找找看了，好久没用了， DemoProject_MM32/Device /MM32F103xCxE_o 这个目录下的SDK不能用吗？

楼主这个工程是我目前从网上能找到唯一的一个正常运行的例程，其它地方，包括官方SDK都不行，但是你这个sdk和我下载用户手册和数据手册都不对应，另外有没有这个SDK的官方历程，我现在调spi，调不通，逻辑分析仪抓取是有波形数据的。要原始SDK的目的主要是，看下附带的例程和手册。

**Comment by JerryZheng89** [comment]
> > SDK版本和芯片的版本要对应，不然可能有问题， 原始SDK我要找找看了，好久没用了， DemoProject_MM32/Device /MM32F103xCxE_o 这个目录下的SDK不能用吗？
> 
> 
> 
> 楼主这个工程是我目前从网上能找到唯一的一个正常运行的例程，其它地方，包括官方SDK都不行，但是你这个sdk和我下载用户手册和数据手册都不对应，另外有没有这个SDK的官方历程，我现在调spi，调不通，逻辑分析仪抓取是有波形数据的。要原始SDK的目的主要是，看下附带的例程和手册。

估计你的芯片不是主流的版本了才会这样，已经邮件发你了官方SDK
